version: "3.8"
services:
  db:
    image: postgres:15
    container_name: yebragi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "51214:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: yebragi_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: supersecretkey
    volumes:
      - .:/usr/src/app
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  db_data:
